version: '3.9'
services:
  app:
    build: .
    container_name: rbmschedule_app
    ports:
      - '8091:80'
    environment:
      - DB_HOST=db
      - DB_USER=rbm_user
      - DB_PASS=rbm_password
      - DB_NAME=rbm_schedule
      - DEBUG_MODE=false
    depends_on:
      - db
    volumes:
      - ./:/var/www/html:cached
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: rbmschedule_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=rbm_schedule
      - MYSQL_USER=rbm_user
      - MYSQL_PASSWORD=rbm_password
    volumes:
      - db_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro
    restart: unless-stopped

volumes:
  db_data:
